version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: release_management_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: release_management_backend
    network_mode: host
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=disable
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      - postgres
    command: sh -c "sleep 10 && ./main"
  frontend:
    build: ./frontend
    container_name: release_management_frontend
    network_mode: host
    depends_on:
      - backend

volumes:
  postgres_data: